apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-static-web
  namespace: dev-web
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-static-web
  template:
    metadata:
      labels:
        app: simple-static-web
    spec:
     containers:
      - name: simple-static-web
        image: 10.10.10.116:8083/simple-static-web:1.0.0
        ports:
          - containerPort: 80
