apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-svc
  namespace: dev-web
spec:
  selector:
    app: nginx-demo
  type: NodePort   # or LoadBalancer if your environment supports it
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # NodePort range 30000-32767
